version: "3.4"

x-global:
  defaults: &defaults
    # restart: unless-stopped
    # build: .
    image: sentry
    depends_on:
      - redis
      - postgres
      - memcached
      # - smtp
    env_file: .env
    environment:
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      # SENTRY_EMAIL_HOST: smtp.exmail.qq.com
      # SENTRY_EMAIL_USER: msg@newbanker.cn
      # SENTRY_EMAIL_PASSWORD: '8gb$$84nk3e274P6)'
      # SENTRY_EMAIL_USE_TLS: True
      # SENTRY_EMAIL_PORT: 465
    volumes:
      - sentry-data:/var/lib/sentry/files
  volumes: &volumes
    # external: true
    driver: local

services:
  # smtp:
  #   restart: unless-stopped
  #   image: tianon/exim4

  memcached:
    restart: unless-stopped
    image: memcached:alpine

  redis:
    restart: unless-stopped
    image: redis:alpine

  postgres:
    restart: unless-stopped
    image: postgres:alpine
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

  web:
    <<: *defaults
    container_name: sentry
    ports:
      - '9000:9000'

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker


volumes:
    sentry-data:
      <<: *volumes
      # external: true
    sentry-postgres:
      <<: *volumes
      # external: true