#!/usr/bin/env python
#encoding=utf8
#author      : Jam < liujianhncn@gmail.com >
#version     : 1.0
#description : 本脚本主要用来创建ori配置文件

VERSION='6.5.4'

apps = ('elasticsearch', 'logstash', 'kibanna')
shorts = ('es', 'ls', 'kb')

assert len(apps) == len(shorts)
for i in range(len(apps)):
    app = apps[i]
    code = shorts[i]

    with open("{}/Dockerfile.ori".format(code), 'w') as f:
        f.write("FROM       {}:{}\n".format(app, VERSION))
        f.write("MAINTAINER Jam < ops@doat.cc >")