---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: aws
  name: aws
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: aws
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: aws
    spec:
      restartPolicy: Always
      # schedulerName: default-scheduler
      # securityContext: {}
      # serviceAccount: default
      # serviceAccountName: default
      # terminationGracePeriodSeconds: 30
      containers:
      - name: aws
        image: hub.newbanker.cn/aws
        imagePullPolicy: Always
        # ports:
        # - containerPort: 80
        #   protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /api/test
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 600
        #   periodSeconds: 60
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /api/test
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 60
        #   periodSeconds: 5
        #   successThreshold: 1
        #   timeoutSeconds: 1
        # terminationMessagePath: /dev/termination-log
        # terminationMessagePolicy: File
        command: ["tail", "-f", "/etc/hosts"]
        # args: ['sh']
        volumeMounts:
        - mountPath: /etc/awstats
          name: aws-conf
        - mountPath: /var/log/nginx/
          name: aws-nglog
          readOnly: true
      volumes:
      - name: aws-conf
        nfs:
          path: /nginx/aws
          server: 1ac8b4a474-nir78.cn-beijing.nas.aliyuncs.com
      - name: aws-nglog
        nfs:
          path: /nginx/history
          server: 1ac8b4a474-nir78.cn-beijing.nas.aliyuncs.com
      # - configMap:
      #     defaultMode: 420
      #     items:
      #     - key: local.js
      #       path: local.js
      #     name: cm-wbs-cms
      #   name: wbs-cms-config
      # - name: default-token-gnc26
      #   secret:
      #     defaultMode: 420
      #     secretName: default-token-gnc26